"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Equal = exports.toQuat = exports.Mix = exports.Scale = exports.Negate = exports.Subtract = exports.Add = exports.Elements = exports.Create = exports.Constant = void 0;
const NodeDescription_js_1 = require("../../../Nodes/NodeDescription.js");
const In1Out1FuncNode_js_1 = require("../../../Nodes/Templates/In1Out1FuncNode.js");
const In2Out1FuncNode_js_1 = require("../../../Nodes/Templates/In2Out1FuncNode.js");
const In3Out1FuncNode_js_1 = require("../../../Nodes/Templates/In3Out1FuncNode.js");
const VecElements_js_1 = require("../Logic/VecElements.js");
const Vec3_js_1 = require("./Internal/Vec3.js");
const Vec4_js_1 = require("./Internal/Vec4.js");
exports.Constant = new NodeDescription_js_1.NodeDescription('math/euler', 'Logic', 'Constant', (description, graph) => new In1Out1FuncNode_js_1.In1Out1FuncNode(description, graph, ['euler'], 'euler', (a) => a));
exports.Create = new NodeDescription_js_1.NodeDescription('math/create/euler', 'Logic', 'CREATE', (description, graph) => new In3Out1FuncNode_js_1.In3Out1FuncNode(description, graph, ['float', 'float', 'float'], 'euler', (x, y, z) => new Vec3_js_1.Vec3(x, y, z), ['x', 'y', 'z']));
exports.Elements = new NodeDescription_js_1.NodeDescription('math/elements/euler', 'Logic', 'CREATE', (description, graph) => new VecElements_js_1.VecElements(description, graph, 'euler', ['x', 'y', 'z'], Vec3_js_1.vec3ToArray));
exports.Add = new NodeDescription_js_1.NodeDescription('math/add/euler', 'Logic', '+', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['euler', 'euler'], 'euler', Vec3_js_1.vec3Add));
exports.Subtract = new NodeDescription_js_1.NodeDescription('math/subtract/euler', 'Logic', '-', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['euler', 'euler'], 'euler', Vec3_js_1.vec3Subtract));
exports.Negate = new NodeDescription_js_1.NodeDescription('math/negate/euler', 'Logic', '-', (description, graph) => new In1Out1FuncNode_js_1.In1Out1FuncNode(description, graph, ['euler'], 'euler', Vec3_js_1.vec3Negate));
exports.Scale = new NodeDescription_js_1.NodeDescription('math/scale/euler', 'Logic', '×', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['euler', 'float'], 'euler', Vec3_js_1.vec3Scale));
exports.Mix = new NodeDescription_js_1.NodeDescription('math/mix/euler', 'Logic', '÷', (description, graph) => new In3Out1FuncNode_js_1.In3Out1FuncNode(description, graph, ['euler', 'euler', 'float'], 'euler', Vec3_js_1.vec3Mix, ['a', 'b', 't']));
exports.toQuat = new NodeDescription_js_1.NodeDescription('math/toQuat/euler', 'Logic', '÷', (description, graph) => new In1Out1FuncNode_js_1.In1Out1FuncNode(description, graph, ['euler'], 'quat', Vec4_js_1.eulerToQuat));
exports.Equal = new NodeDescription_js_1.NodeDescription('math/equal/euler', 'Logic', '=', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['euler', 'euler'], 'boolean', Vec3_js_1.vec3Equals));
