"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Equal = exports.Mix = exports.Dot = exports.Cross = exports.Normalize = exports.Length = exports.Scale = exports.Negate = exports.Subtract = exports.Add = exports.Elements = exports.Create = exports.Constant = void 0;
const NodeDescription_js_1 = require("../../../Nodes/NodeDescription.js");
const In1Out1FuncNode_js_1 = require("../../../Nodes/Templates/In1Out1FuncNode.js");
const In2Out1FuncNode_js_1 = require("../../../Nodes/Templates/In2Out1FuncNode.js");
const In3Out1FuncNode_js_1 = require("../../../Nodes/Templates/In3Out1FuncNode.js");
const VecElements_js_1 = require("../Logic/VecElements.js");
const Vec3_js_1 = require("./Internal/Vec3.js");
exports.Constant = new NodeDescription_js_1.NodeDescription('math/vec3', 'Logic', 'Constant', (description, graph) => new In1Out1FuncNode_js_1.In1Out1FuncNode(description, graph, ['vec3'], 'vec3', (a) => a));
exports.Create = new NodeDescription_js_1.NodeDescription('math/create/vec3', 'Logic', 'CREATE', (description, graph) => new In3Out1FuncNode_js_1.In3Out1FuncNode(description, graph, ['float', 'float', 'float'], 'vec3', (x, y, z) => new Vec3_js_1.Vec3(x, y, z), ['x', 'y', 'z']));
exports.Elements = new NodeDescription_js_1.NodeDescription('math/elements/vec3', 'Logic', 'CREATE', (description, graph) => new VecElements_js_1.VecElements(description, graph, 'vec3', ['x', 'y', 'z'], Vec3_js_1.vec3ToArray));
exports.Add = new NodeDescription_js_1.NodeDescription('math/add/vec3', 'Logic', '+', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['vec3', 'vec3'], 'vec3', Vec3_js_1.vec3Add));
exports.Subtract = new NodeDescription_js_1.NodeDescription('math/subtract/vec3', 'Logic', '-', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['vec3', 'vec3'], 'vec3', Vec3_js_1.vec3Subtract));
exports.Negate = new NodeDescription_js_1.NodeDescription('math/negate/vec3', 'Logic', '-', (description, graph) => new In1Out1FuncNode_js_1.In1Out1FuncNode(description, graph, ['vec3'], 'vec3', Vec3_js_1.vec3Negate));
exports.Scale = new NodeDescription_js_1.NodeDescription('math/scale/vec3', 'Logic', '×', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['vec3', 'float'], 'vec3', Vec3_js_1.vec3Scale));
exports.Length = new NodeDescription_js_1.NodeDescription('math/length/vec3', 'Logic', 'LENGTH', (description, graph) => new In1Out1FuncNode_js_1.In1Out1FuncNode(description, graph, ['vec3'], 'float', Vec3_js_1.vec3Length));
exports.Normalize = new NodeDescription_js_1.NodeDescription('math/normalize/vec3', 'Logic', 'NORMALIZE', (description, graph) => new In1Out1FuncNode_js_1.In1Out1FuncNode(description, graph, ['vec3'], 'vec3', Vec3_js_1.vec3Normalize));
exports.Cross = new NodeDescription_js_1.NodeDescription('math/cross/vec3', 'Logic', 'CROSS', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['vec3', 'vec3'], 'vec3', Vec3_js_1.vec3Cross));
exports.Dot = new NodeDescription_js_1.NodeDescription('math/dot/vec3', 'Logic', 'DOT', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['vec3', 'vec3'], 'float', Vec3_js_1.vec3Dot));
exports.Mix = new NodeDescription_js_1.NodeDescription('math/mix/vec3', 'Logic', '÷', (description, graph) => new In3Out1FuncNode_js_1.In3Out1FuncNode(description, graph, ['vec3', 'vec3', 'float'], 'vec3', Vec3_js_1.vec3Mix, ['a', 'b', 't']));
exports.Equal = new NodeDescription_js_1.NodeDescription('math/equal/vec3', 'Logic', '=', (description, graph) => new In2Out1FuncNode_js_1.In2Out1FuncNode(description, graph, ['vec3', 'vec3'], 'boolean', Vec3_js_1.vec3Equals));
